// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXQUa6aMwKGfjWeF2kuE52Hb38BNVhKVU',
    appId: '1:197466207172:web:03829df7fdd5d61fbaaa91',
    messagingSenderId: '197466207172',
    projectId: 'inventary-5897f',
    authDomain: 'inventary-5897f.firebaseapp.com',
    storageBucket: 'inventary-5897f.appspot.com',
    measurementId: 'G-DT19X8YG3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBL-E7Bpw1h1hCMhKv1HbTRcoUqZ_qI6A',
    appId: '1:197466207172:android:c95e7f7ec0d456cbbaaa91',
    messagingSenderId: '197466207172',
    projectId: 'inventary-5897f',
    storageBucket: 'inventary-5897f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzdtlfPeL3ad2DjUBtvJR3HqGTtZxUga8',
    appId: '1:197466207172:ios:acc9e5720bbefd76baaa91',
    messagingSenderId: '197466207172',
    projectId: 'inventary-5897f',
    storageBucket: 'inventary-5897f.appspot.com',
    iosBundleId: 'com.example.inventary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXQUa6aMwKGfjWeF2kuE52Hb38BNVhKVU',
    appId: '1:197466207172:web:5cf6d0b7d4befb53baaa91',
    messagingSenderId: '197466207172',
    projectId: 'inventary-5897f',
    authDomain: 'inventary-5897f.firebaseapp.com',
    storageBucket: 'inventary-5897f.appspot.com',
    measurementId: 'G-5MWGPPXQWR',
  );

}